/**
 * 11 Core Essay Editing Principles (Enhanced with Expert Insights)
 * These principles guide the AI feedback generation
 * Sources: Harvard, CollegeVine, College Essay Guy, AdmitReport
 */

export interface EssayPrinciple {
  id: string;
  name: string;
  description: string;
  weight: number; // Importance weight (1-10)
  evaluationPrompt: string;
}

export const ESSAY_PRINCIPLES: EssayPrinciple[] = [
  {
    id: 'hook',
    name: 'Compelling Hook',
    description: 'The essay starts with an engaging opening that captures attention',
    weight: 9,
    evaluationPrompt: `Evaluate the essay's opening hook. Does it:
- Immediately capture the reader's attention?
- Set the tone for the rest of the essay?
- Avoid clichés and generic openings?
- Create curiosity or emotional engagement?
Provide specific suggestions for improvement.`,
  },
  {
    id: 'show-dont-tell',
    name: 'Show, Don\'t Tell',
    description: 'Uses specific examples and vivid details instead of abstract statements',
    weight: 10,
    evaluationPrompt: `Analyze how the essay uses "show, don't tell":
- Identify instances where the writer tells instead of shows
- Find opportunities to add specific examples, sensory details, or anecdotes
- Suggest concrete scenes or moments that could replace abstract statements
- Ensure the reader can visualize and feel the experiences described`,
  },
  {
    id: 'authenticity',
    name: 'Authentic Voice',
    description: 'Maintains a genuine, personal voice that reflects the student',
    weight: 10,
    evaluationPrompt: `Assess the authenticity of the voice:
- Does it sound like a real person, not a textbook or generic applicant?
- Are there unique phrases or perspectives that reveal personality?
- Identify any overly formal or pretentious language
- Check for RED FLAGS that signal inauthenticity:
  * Thesaurus abuse: utilize, plethora, myriad, endeavor (instead of simple words)
  * Excessive passive voice: "I was taught", "It was shown", "The experience gave me"
  * Resume repetition: just listing accomplishments without new insights
  * Wikipedia voice: overly encyclopedic or academic tone
  * Formulaic language: "In today's society", "Since the dawn of time"
- Check for AI WRITING PATTERNS (major red flags):
  * EXCESSIVE EM DASH USE (—): More than 2-3 em dashes is a strong AI tell
  * "It's Not About X, It's About Y" formula: This is tired and formulaic
  * Excessive tricolon (groups of three): Overusing three-part structures
  * Enthusiasm overload: Every sentence trying to be profound or excited
  * Setup-payoff structure: Rhetorical questions followed by generic explanations
- Does the essay provide NEW information not found in transcripts/activities lists?
- Does the writing sound like it could have been generated by AI? (Flag specifically if yes)
- Suggest ways to make the voice more natural and genuine`,
  },
  {
    id: 'structure',
    name: 'Clear Structure',
    description: 'Has a logical flow with smooth transitions between ideas',
    weight: 8,
    evaluationPrompt: `Evaluate the essay's structure and flow:
- Does each paragraph connect logically to the next?
- Are transitions smooth and purposeful?
- Is there a clear progression of ideas or narrative arc?
- Suggest improvements to organization or paragraph order`,
  },
  {
    id: 'specificity',
    name: 'Specific Details',
    description: 'Uses concrete, specific details rather than vague generalizations',
    weight: 9,
    evaluationPrompt: `Check for specificity:
- Identify vague or generic statements
- Find opportunities to add specific numbers, names, places, or moments
- Replace general descriptions with precise details
- Ensure claims are supported with concrete examples`,
  },
  {
    id: 'reflection',
    name: 'Meaningful Reflection',
    description: 'Demonstrates insight and growth through thoughtful reflection',
    weight: 10,
    evaluationPrompt: `Analyze the depth of reflection:
- Does the essay go beyond describing what happened to exploring why it matters?
- Is there evidence of self-awareness and personal growth?
- Are the insights genuine and meaningful, not forced?
- VULNERABILITY & AUTHENTICITY:
  * Does the writer show authentic vulnerability or take emotional risks?
  * Are they willing to reveal flaws, mistakes, or moments of uncertainty?
  * Avoid essays that present a "perfect" persona
- SOPHISTICATION & NUANCE:
  * Does the reflection show complex, nuanced thinking (not black-and-white)?
  * Is there intellectual curiosity or engagement with ideas?
  * Does the essay reveal multiple dimensions of the student's identity?
  * Are insights specific and original, not generic ("I learned perseverance")?
- DEPTH OF INSIGHT:
  * Does it connect personal experiences to broader themes or values?
  * Is there evidence of genuine character development?
  * Does it show how experiences shaped who they are today?
- Suggest ways to deepen the reflection or connect experiences to values`,
  },
  {
    id: 'focus',
    name: 'Focused Topic',
    description: 'Stays focused on a single theme without trying to cover too much',
    weight: 8,
    evaluationPrompt: `Assess the essay's focus:
- Is there one clear central theme or story?
- Does the essay try to cover too many different ideas?
- Are there tangents or unnecessary details that could be cut?
- Check for CLICHÉ TOPICS that need unique treatment:
  * Sports injury/championship → Only acceptable if told from a truly unique angle
  * Immigrant story → Must go beyond generic "two cultures" narrative
  * Community service → Avoid savior complex, focus on what YOU learned
  * Mission trip → Same as above
  * Death of loved one → Must show growth beyond "I learned to appreciate life"
  * "The day I became an adult" → Usually too generic
- Is this a BROAD BIOGRAPHICAL narrative (covering too much of life)?
- Does the essay provide a specific, focused moment or period rather than a life summary?
- Suggest ways to narrow or sharpen the focus`,
  },
  {
    id: 'word-choice',
    name: 'Precise Word Choice',
    description: 'Uses strong, active verbs and precise language',
    weight: 7,
    evaluationPrompt: `Evaluate word choice and language:
- Identify weak verbs (is, was, has) that could be stronger
- Find opportunities to use more precise, vivid vocabulary
- Look for redundant phrases or wordiness
- Check for OVERUSED METAPHORS and clichés:
  * "tapestry" (of experiences/cultures)
  * "mosaic" (of identities)
  * "journey" (life is a journey)
  * "puzzle pieces" (coming together)
  * "melting pot"
  * "landscape" (of opportunities)
  * "bridge" (between cultures)
  * "path" or "road" (less traveled)
- Flag generic descriptors: "amazing", "incredible", "life-changing" (without specifics)
- Identify cliché expressions: "at the end of the day", "think outside the box"
- Ensure language matches the intended tone and voice
- Suggest more original, specific alternatives`,
  },
  {
    id: 'conclusion',
    name: 'Strong Conclusion',
    description: 'Ends with impact, tying together themes without simply repeating',
    weight: 8,
    evaluationPrompt: `Analyze the conclusion:
- Does it bring the essay to a satisfying close?
- Does it avoid simply repeating what was already said?
- Does it leave the reader with a lasting impression or insight?
- Suggest ways to strengthen the ending`,
  },
  {
    id: 'grammar-mechanics',
    name: 'Grammar & Mechanics',
    description: 'Free from grammatical errors and typos',
    weight: 6,
    evaluationPrompt: `Check for grammar and mechanics:
- Identify any grammatical errors
- Look for typos or spelling mistakes
- Check punctuation and sentence structure
- Ensure consistency in tense and voice
- Flag any confusing or awkwardly constructed sentences`,
  },
  {
    id: 'originality',
    name: 'Originality & Distinction',
    description: 'Offers a unique perspective that distinguishes the applicant',
    weight: 9,
    evaluationPrompt: `Evaluate the essay's originality and distinctiveness:
- UNIQUE PERSPECTIVE:
  * Does this essay offer something fresh or unexpected?
  * Could this essay have been written by any other applicant, or is it distinctly THIS person?
  * Are there unique observations, perspectives, or connections?
- AVOIDING GENERIC APPROACHES:
  * Does the essay go beyond surface-level treatment of the topic?
  * If using a common topic, is the approach truly original?
  * Does it reveal something specific about THIS student's character/values?
- MEMORABLE QUALITY:
  * Will an admissions officer remember this essay among hundreds?
  * Are there specific details, insights, or moments that stand out?
  * Does it reveal the student's personality in a distinctive way?
- AUTHENTIC DIFFERENTIATION:
  * What makes this applicant different from peers?
  * How does this essay showcase their unique qualities/experiences?
  * Is the uniqueness authentic, not forced or contrived?
- Suggest ways to make the essay more distinctive and memorable`,
  },
];

/**
 * Generate a comprehensive evaluation prompt that covers all principles
 */
export function generateEssayEvaluationPrompt(essay: string, prompt: string, format: 'json' | 'markdown' = 'json'): string {
  if (format === 'json') {
    const principlesList = ESSAY_PRINCIPLES.map((p, i) => `${i + 1}. ${p.name} (ID: ${p.id})`).join('\n');

    return `You are an expert college essay editor. Analyze the following essay and provide feedback in JSON format.

PROMPT: ${prompt}

ESSAY: ${essay}

Evaluate across these ${ESSAY_PRINCIPLES.length} principles:
${principlesList}

Respond with ONLY valid JSON (no markdown, no code blocks):

{
  "overallScore": <number 0-100>,
  "overallAssessment": "<brief summary>",
  "principlesFeedback": [${ESSAY_PRINCIPLES.map(p => `
    {"principleId":"${p.id}","principleName":"${p.name}","score":<1-10>,"feedback":"<analysis>","suggestions":["<tip1>","<tip2>"]}`).join(',')}
  ],
  "priorityImprovements": [
    {"rank":1,"title":"<title>","description":"<desc>","principleIds":["<id>"]}
  ],
  "inlineComments": [
    {"section":"<section>","comment":"<comment>","priority":"<high|medium|low>"}
  ],
  "strengths": ["<strength1>","<strength2>"],
  "weaknesses": ["<weakness1>","<weakness2>"],
  "wordCount": <number>
}

CRITICAL: Return ONLY the JSON object. No text before or after. All ${ESSAY_PRINCIPLES.length} principles required.`;
  }

  // Markdown format
  return `You are an expert college essay editor. Analyze the following essay against the college application prompt and provide detailed, actionable feedback.

PROMPT:
${prompt}

ESSAY:
${essay}

Please evaluate this essay across these key principles:

${ESSAY_PRINCIPLES.map(
  (p) => `
**${p.name}** (Importance: ${p.weight}/10)
${p.description}
${p.evaluationPrompt}
`
).join('\n')}

Provide your feedback in the following format:

## Overall Assessment
[Brief summary of the essay's strengths and areas for improvement]

## Principle-by-Principle Feedback

${ESSAY_PRINCIPLES.map((p) => `### ${p.name}\n**Score:** [X/10]\n**Feedback:**\n[Detailed analysis]\n**Suggestions:**\n[Specific, actionable improvements]`).join('\n\n')}

## Priority Improvements
[List 3-5 most important changes to make, in order of priority]

## Inline Comments
[Specific line-by-line suggestions formatted as: "Line X: [comment]"]

Keep all feedback constructive, specific, and actionable. Focus on helping the student's voice shine through while meeting college application standards.`;
}

/**
 * Generate a prompt for essay customization with school-specific context
 * @deprecated Use generateTopicAwareCustomizationPrompt instead for better context matching
 */
export function generateCustomizationPrompt(
  essay: string,
  schoolName: string,
  majorName: string,
  schoolContext: {
    programDescription: string;
    keyFeatures: string[];
    keywords: string[];
  }
): string {
  return `You are an expert college essay editor specializing in school-specific customization.

TASK: Make MINIMAL, TARGETED edits to customize this essay for ${schoolName}'s ${majorName} program. Your edits should be surgical and conservative—only adding 1-3 specific program details where they fit naturally.

ORIGINAL ESSAY:
${essay}

SCHOOL/PROGRAM CONTEXT:
Program: ${schoolName} - ${majorName}

Program Description:
${schoolContext.programDescription}

Key Features:
${schoolContext.keyFeatures.map((f, i) => `${i + 1}. ${f}`).join('\n')}

Important Keywords: ${schoolContext.keywords.join(', ')}

CRITICAL REQUIREMENTS:
1. **TARGETED CHANGES** - Make strategic edits to effectively customize for the program
2. **PRESERVE 80%+ OF ORIGINAL TEXT** - Keep most of the original wording intact
3. Make 2-5 targeted additions or modifications that connect the essay to the program
4. You MAY rewrite sentences if it creates a more natural connection to program features
5. DO NOT change the student's core voice, tone, or narrative structure
6. Add program details where they create meaningful connections to the student's story
7. Ensure all customizations feel authentic and well-integrated

CUSTOMIZATION APPROACH:
- Look for 2-4 spots where program-specific details would strengthen the essay
- Add specific course names, professors, research opportunities, or program features that connect to the student's interests
- Can modify existing sentences to weave in program details naturally
- The conclusion and opening can be adjusted if it strengthens the school connection
- Balance between customization and authenticity

AVOID:
❌ Rewriting large sections
❌ Adding multiple paragraphs of program details
❌ Changing the student's original word choices
❌ Making the essay sound generic or template-like
❌ Forcing program details where they don't fit naturally

Respond with ONLY valid JSON (no markdown, no code blocks):

{
  "customizedEssay": "<the full customized essay text>",
  "changesSummary": [
    {
      "location": "<paragraph or section reference>",
      "change": "<description of what was added/changed>",
      "reason": "<why this change was made>"
    }
  ],
  "integrationNotes": "<overall explanation of how customizations maintain authenticity and connect to the original narrative>",
  "changeCount": <number of actual changes made>,
  "preservationPercentage": <estimated % of original text preserved>
}

Remember: Less is more. The goal is subtle, strategic customization, not extensive rewriting. Return ONLY the JSON object.`;
}

/**
 * Generate a topic-aware customization prompt
 * Uses essay topics to match relevant school context (activities, culture, or academics)
 */
export function generateTopicAwareCustomizationPrompt(
  essay: string,
  schoolName: string,
  majorName: string,
  context: import('@/types/school-data').CustomizationContext
): string {
  // Build context sections based on what's available
  let contextSection = `SCHOOL: ${schoolName}\nMAJOR: ${majorName}\n\n`;

  // Academic context (for academically-focused essays)
  if (context.academicContext) {
    contextSection += `ACADEMIC PROGRAM:\n`;
    contextSection += `${context.academicContext.programDescription}\n\n`;
    contextSection += `Key Features:\n`;
    contextSection += context.academicContext.keyFeatures.map((f, i) => `${i + 1}. ${f}`).join('\n');
    contextSection += '\n\n';

    if (context.academicContext.researchOpportunities.length > 0) {
      contextSection += `Research Opportunities:\n`;
      contextSection += context.academicContext.researchOpportunities.map(r => `- ${r}`).join('\n');
      contextSection += '\n\n';
    }
  }

  // Activity context (for personal/extracurricular essays)
  if (context.activityContext && Object.keys(context.activityContext).length > 0) {
    contextSection += `RELEVANT CAMPUS ACTIVITIES:\n`;
    contextSection += `(The essay mentions these student activities, so reference relevant campus opportunities)\n\n`;

    Object.entries(context.activityContext).forEach(([activity, opportunities]) => {
      contextSection += `${activity.charAt(0).toUpperCase() + activity.slice(1)}:\n`;
      contextSection += opportunities.map(o => `- ${o}`).join('\n');
      contextSection += '\n\n';
    });
  }

  // Values/culture context (for reflective essays)
  if (context.valuesContext) {
    contextSection += `CAMPUS CULTURE & VALUES:\n`;

    if (context.valuesContext.traditions.length > 0) {
      contextSection += `Traditions: ${context.valuesContext.traditions.join(', ')}\n`;
    }

    if (context.valuesContext.communityAspects.length > 0) {
      contextSection += `Community: ${context.valuesContext.communityAspects.join(', ')}\n`;
    }

    if (context.valuesContext.leadershipOpportunities.length > 0) {
      contextSection += `Leadership: ${context.valuesContext.leadershipOpportunities.join(', ')}\n`;
    }

    contextSection += '\n';
  }

  // Culture highlights (always included)
  if (context.cultureHighlights.length > 0) {
    contextSection += `SCHOOL CULTURE HIGHLIGHTS:\n`;
    contextSection += context.cultureHighlights.map(h => `- ${h}`).join('\n');
    contextSection += '\n';
  }

  return `You are an expert college essay editor specializing in school-specific customization.

TASK: Make TARGETED, AUTHENTIC edits to customize this essay for ${schoolName}. Your customizations should connect the student's story with relevant aspects of ${schoolName}'s campus.

ORIGINAL ESSAY:
${essay}

${contextSection}

CRITICAL CUSTOMIZATION STRATEGY:
1. **MATCH ESSAY TONE** - If the essay is personal/extracurricular, reference campus activities (clubs, sports, arts). If academic, reference programs/research.
2. **PRESERVE 80%+ OF ORIGINAL TEXT** - Keep most of the original wording intact
3. **AUTHENTIC CONNECTIONS** - Only add school details that genuinely connect to the student's story
4. Make 2-5 targeted additions or modifications
5. DO NOT force academic program details into personal essays about hobbies/activities
6. DO NOT change the student's core voice, tone, or narrative structure

EXAMPLES OF GOOD CUSTOMIZATION:
✅ Essay about chess → "excited to join Princeton's Chess Club"
✅ Essay about basketball → "looking forward to intramural basketball at Stanford"
✅ Essay about music → "eager to perform with UT Austin's music ensembles"
✅ Essay about research → "drawn to Professor X's lab studying Y"
✅ Essay about values → "resonates with MIT's collaborative culture"

EXAMPLES OF BAD CUSTOMIZATION:
❌ Essay about chess → forcing in "Computer Science curriculum"
❌ Essay about music → awkwardly mentioning "engineering facilities"
❌ Personal story → inserting academic program details that don't fit

CUSTOMIZATION APPROACH:
- Identify 2-4 natural connection points where school-specific details strengthen the narrative
- If the essay is about extracurriculars, reference relevant campus activities/clubs
- If the essay is academic, reference specific programs, courses, or research
- The conclusion is often the best place for school connections
- Ensure all additions feel organic and authentic

Respond with ONLY valid JSON (no markdown, no code blocks):

{
  "customizedEssay": "<the full customized essay text>",
  "changesSummary": [
    {
      "location": "<paragraph or section reference>",
      "change": "<description of what was added/changed>",
      "reason": "<why this change was made and how it connects to the essay's theme>"
    }
  ],
  "integrationNotes": "<explanation of how customizations maintain authenticity and match the essay's tone (personal vs academic)>",
  "changeCount": <number of actual changes made>,
  "preservationPercentage": <estimated % of original text preserved>
}

Remember: The goal is to show genuine interest in the school by connecting the student's authentic story with relevant campus opportunities. Return ONLY the JSON object.`;
}

/**
 * Generate a prompt for complete essay rewrite
 */
export function generateRewritePrompt(
  essay: string,
  prompt: string,
  focusAreas: string[],
  wordLimit?: number
): string {
  const focusSection =
    focusAreas.length > 0 ? `\n\nFocus especially on improving:\n${focusAreas.map((f) => `- ${f}`).join('\n')}` : '';

  // Extract word limit from prompt if not provided
  let targetWordLimit = wordLimit;
  if (!targetWordLimit) {
    const wordLimitMatch = prompt.match(/(\d+)\s*word/i);
    if (wordLimitMatch) {
      targetWordLimit = parseInt(wordLimitMatch[1]);
    }
  }

  // If no word limit detected, use original essay length + 10 words
  if (!targetWordLimit) {
    const originalWordCount = essay.trim().split(/\s+/).filter(Boolean).length;
    targetWordLimit = originalWordCount + 10;
  }

  const wordLimitSection = `\n\n**CRITICAL WORD LIMIT**: The rewritten essay MUST NOT exceed ${targetWordLimit} words. Count carefully and stay within this limit.`;

  return `You are an expert college essay editor. Rewrite the following essay to significantly improve its quality while maintaining the student's authentic voice and core story.

ORIGINAL PROMPT:
${prompt}

CURRENT ESSAY:
${essay}
${focusSection}
${wordLimitSection}

REWRITING GUIDELINES:
1. Keep the core narrative and personal story
2. Maintain the student's authentic voice
3. Apply the "show, don't tell" principle throughout
4. Add specific, vivid details
5. Strengthen the opening hook
6. Deepen reflection and insights
7. Improve flow and transitions
8. Use stronger, more precise language
9. Ensure a powerful conclusion
10. Sound natural and human - avoid AI writing patterns

**CRITICAL: Avoid These AI Writing Clichés**
Your rewrite must sound like a real student wrote it. Avoid these overused devices:

❌ AVOID:
1. Excessive Em Dash Use (—) - Use sparingly, if at all
2. The "It's Not About X, It's About Y" Formula - This is tired and formulaic
3. Excessive Tricolon use (groups of three) - Vary your sentence structures naturally
4. The Wikipedia Voice - No encyclopedic or overly formal tone
5. The "tapestry", "landscape" and "In today's [adjective] world" metaphors - These are AI tells
6. Enthusiasm overload - Not every sentence needs to be excited or profound
7. The setup-payoff structure - Avoid rhetorical questions followed by surprisingly generic explanations

✅ DO:
- Write with natural, conversational rhythm
- Use varied sentence lengths and structures
- Include authentic teenage voice and perspective
- Be specific and concrete, not grandiose
- Let insights emerge naturally from the story
- Use simple, direct language where appropriate
- Show personality through unique word choices and observations

Please provide:

## Rewritten Essay
[The significantly improved version - must respect word limit if specified]

## Key Changes Made
[Bulleted list of major improvements with before/after examples]

## Rationale
[Brief explanation of the strategic choices in the rewrite]

Remember: This should feel like the student's best work, not like it was written by someone else or an AI.`;
}

/**
 * Get total weight of all principles
 */
export function getTotalWeight(): number {
  return ESSAY_PRINCIPLES.reduce((sum, p) => sum + p.weight, 0);
}

/**
 * Calculate overall essay score based on principle scores
 */
export function calculateOverallScore(principleScores: Record<string, number>): number {
  const totalWeight = getTotalWeight();
  const weightedSum = ESSAY_PRINCIPLES.reduce((sum, principle) => {
    const score = principleScores[principle.id] || 0;
    return sum + score * principle.weight;
  }, 0);

  return Math.round((weightedSum / (totalWeight * 10)) * 100);
}
